# Generated by Django 4.1 on 2023-02-15 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShadzStore', '0004_orderdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderDetails',
            new_name='OrderDetail',
        ),
    ]
