# Generated by Django 4.1 on 2023-02-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShadzStore', '0005_rename_orderdetails_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
