# Generated by Django 4.1 on 2023-02-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShadzStore', '0008_orderupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('accountID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='user', max_length=70)),
                ('email', models.CharField(default='', max_length=90)),
                ('phone', models.IntegerField(default=0)),
                ('account_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
