# Generated by Django 4.1 on 2023-02-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Blog Post Title', max_length=50)),
                ('thumbnail', models.ImageField(default='', upload_to='')),
                ('head0', models.CharField(default='Heading 0', max_length=500)),
                ('head1', models.CharField(default='Heading 1', max_length=500)),
                ('head2', models.CharField(default='Heading 2', max_length=500)),
                ('published_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
