# Generated by Django 4.1 on 2023-02-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShadzBlogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_head0',
            field=models.CharField(default='Heading 0', max_length=5000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_head1',
            field=models.CharField(default='Heading 1', max_length=5000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_head2',
            field=models.CharField(default='Heading 2', max_length=5000),
        ),
    ]
