# Generated by Django 4.1 on 2023-02-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShadzBlogs', '0004_alter_blogpost_content_head0_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='email',
            field=models.EmailField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='writer',
            field=models.CharField(default='Anonymous', max_length=60),
        ),
    ]
